Update action.yml

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -418,3 +418,42 @@ runs:
           name: kernel-${{ env.CONFIG }}
           path: |
             *.zip
+            
+cp ../../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch ./common/ 
+          cp ../../susfs4ksu/kernel_patches/fs/* ./common/fs/ 
+          cp ../../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
+
+
+          case "$susfs_version" in 
+            "v1.5.5"|"v1.5.6"|"v1.5.7") 
+              cp "../../../kernel_patches/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch" "./ksun_susfs_latest.patch" 
+              ;; 
+            "v1.5.8"|"v1.5.9") 
+              cp ../../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./ 
+              patch -p1 --forward --fuzz=3 < 10_enable_susfs_for_ksu.patch || true 
+              cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_apk_sign.c.patch" ./ 
+              patch -p1 --forward --fuzz=3 < fix_apk_sign.c.patch 
+              cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_core_hook.c.patch" ./ 
+              patch -p1 --forward --fuzz=3 < fix_core_hook.c.patch 
+              cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_selinux.c.patch" ./ 
+              patch -p1 --forward --fuzz=3 < fix_selinux.c.patch 
+              cp "../../../kernel_patches/next/susfs_fix_patches/$susfs_version/fix_ksud.c.patch" ./ 
+              patch -p1 --forward --fuzz=3 < fix_ksud.c.patch 
+              ;; 
+            *) 
+              echo "Invalid version: $susfs_version" 
+              exit 1 
+              ;; 
+          esac 
+          patch -p1 --forward < ksun_susfs_latest.patch || true
+
+          # Change to common directory and apply SUSFS patch 
+          cd ../common 
+          if [ "${{ inputs.android_version }}" = "android15" ] && [ "${{ inputs.kernel_version }}" = "6.6" ]; then 
+              if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c; then 
+                  sed -i '/#include <trace\/hooks\/blk.h>/a #include <trace\/hooks\/fs.h>' ./fs/namespace.c 
+              else 
+                  echo "Line already present. Skipping insert." 
+              fi 
+          fi 
+          patch -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
